### ISSUE TITLE
Accessing Rails.env in a model results in an error

### ISSUE THREAD

**Issue by thomaswitt** [aws/aws-record-rails#16] opened 2024-11-27 12:35 UTC
### Describe the bug

I can't use Rails.env (e.g. Rails.env.test?) anymore in Models, resulting in:

```
     Failure/Error: return if Rails.env.test?

     NoMethodError:
       undefined method `env' for module Aws::Record::Rails
     # ./app/models/user.rb:121:in `email_is_unique'
     # ./spec/models/user_spec.rb:30:in `block (3 levels) in <top (required)>'
```

Only when I use `::Rails.env.test?` it works.

### Expected Behavior

Rails.env should have the expected behavior

### Current Behavior

Rails.env is not available, only ::Rails.env

### Reproduction Steps

Access Rails.env in any model.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-record-rails latest

### Environment details (Version of Ruby, OS environment)

Ruby 3.3.6 macos

**Comment by mullermp** [comment] 2024-11-27 12:39
Could you please share your model and example code causing this?

**Comment by thomaswitt** [comment] 2024-11-27 12:42
```
class User < BaseModel
  include Aws::Record
  include ActiveModel::Validations

  string_attr :user_email
  string_attr :name
  string_attr :first_name
  string_attr :last_name
  string_attr :language
  string_attr :telegram_username

  validates_presence_of :user_email
  validates_presence_of :name
  validate :test_me

  global_secondary_index(:user_email_gsi,
                         hash_key: :user_email,
                         projection: { projection_type: 'ALL' })

  # FIXME https://github.com/aws/aws-sdk-ruby-record/issues/143
  # global_secondary_index(:telegram_username_gsi,
  #                        hash_key: :telegram_username,
  #                        projection: { projection_type: 'ALL' })

  def test_me
    return if Rails.env.test?
    errors.add(:user_email, "can't be blank") if user_email.blank?
  end
end

```

**Comment by mullermp** [comment] 2024-11-27 13:02
Ok. So the issue is definitely with my refactoring: https://github.com/aws/aws-record-rails/blob/main/lib%2Faws-record-rails.rb#L17

Option 1 - Remove the rails module, just add a railtie, and put the version under that. This may be confusing and conflict with the aws-record gem version.

Option 2 - Acknowledge this as breakage and customers roll forward small fixes. Using a root namespace is often necessary and preferential.

Option 3 - Similar to 2, drop this gem if you don't use it. Requires upgrading to aws-sdk-rails 5. It is included by default in 4.2 to avoid breaking change in a minor version.

**Comment by thomaswitt** [comment] 2024-11-27 13:38
@mullermp I am actually using aws-sdk-rails. Do I need to remove gem 'aws-record-rails' from my gemfile? I thought with v5 I HAVE to actively add it, like i also do with aws-activejob-sqs.

**Comment by mullermp** [comment] 2024-11-27 13:41
No, with v5 all of the gems are modular. If you are not using sqs active job or the aws-record model/scaffold generators, you can remove them from your Gemfile.

I think for your cases, you are using only aws-record and aws-actiondispatch-dynamodb.

**Comment by mullermp** [comment] 2024-11-27 13:46
Please see https://github.com/aws/aws-sdk-rails/issues/165

If there are any confusing bits I can clarify them in the post.

As far as a fix for this, let me think about whether to remove the rails namespace or not..

**Closed** 2024-11-27 19:43 UTC
Labels: bug, needs-triage
